language: node_js
node_js:
  - "10"
  - "8"

script: npm test

jobs:
  include:
    - stage: release
      if: branch = master
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
